workflows:
  FloreriaFleurWork: # Puedes darle el nombre que desees a tu flujo de trabajo
    name: My React Native Workflow
    environment:
      react-native: default # Utiliza la configuración predeterminada para React Native
    scripts:
      # Comandos para instalar dependencias y construir la aplicación
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS
        script: |
          npx react-native run-ios --configuration Release
      # Si necesitas compilar para Android, puedes agregar un paso similar aquí
    artifacts:
      # Archivos que deseas guardar como resultados de la compilación
      - build/ios/*.ipa