workflows:
  react-native:
    name: React Native App
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Run tests
        script: |
          npm test
      - name: Build Android app
        script: |
          npx react-native run-android
      - name: Build iOS app
        script: |
          npx react-native run-ios
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log