workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    scripts:
      - name: Install npm dependencies
        script: | 
          npm install
      - name: Build IPA for distribution
        script: | 
          npx react-native run-ios --configuration Release
          mkdir -p $CM_BUILD_DIR/ios/ipa
          xcodebuild -exportArchive -archivePath $HOME/Library/Developer/Xcode/Archives/<nombre_de_tu_proyecto>.xcarchive -exportPath $CM_BUILD_DIR/ios/ipa -exportOptionsPlist exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log